import Header from '@/components/header';
import Footer from '@/components/footer';
import Menu from '@/components/menu';
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Menu/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
